GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/2 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Freshcoww",
    "number": "2222"
}

###
GET https://fsophonebook-5w03.onrender.com/api/persons
# Success

###
POST https://fsophonebook-5w03.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Bat",
    "number": "123456"
}

###
DELETE https://fsophonebook-5w03.onrender.com/api/persons/1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64950f5afb28eb117a5b435b

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Freshcow",
    "number": "222222"
}